### ISSUE TITLE
RedisLocalConfig 

### ISSUE THREAD

**Issue by bermudezjuanry** [rossr3-pivotal/spring-boot-rest-redis-tutorial#1]
Hi, i'm following this tutorial but a this step:
$ redis-cli hgetall persons
1) "bobevans@someplace.com"
2) "{\"firstName\":\"Bob\",\"lastName\":\"Evans\",\"emailAddress\":\"bobevans@someplace.com\"}"
3) "johndoe@nowhere.com"
4) "{\"firstName\":\"John\",\"lastName\":\"Doe\",\"emailAddress\":\"johndoe@nowhere.com\"}"
5) "jane@somewhere.com"
6) "{\"firstName\":\"Jane\",\"lastName\":\"Smith\",\"emailAddress\":\"jane@somewhere.com\"}"

i get this:
redis 127.0.0.1:6379> hgetall persons
(empty list or set)

using Redis on Windows 10, Intellij and Redis 2.4.6

I need build an REST API with java and Redis
![image](https://user-images.githubusercontent.com/25011615/34058609-04fe5c8c-e1b2-11e7-8188-e06e31814fe3.png)

**Comment by rossr3-pivotal** [comment]
Are there any exceptions or indications from the log files that would indicate there is a problem?

**Comment by bermudezjuanry** [comment]
No, im gonna try on Ubuntu today, if is any problem, i'll write again

**Comment by bermudezjuanry** [comment]
I have the same problem, in logs files is nothing about redis, what can i do?

**Comment by rossr3-pivotal** [comment]
There are too many factors for me to know what exactly is going on. What version of Java are you using? What version of Spring Boot? What version of Redis? When I put this tutorial together, it was done on a mac, using Java 8, Spring Boot 1.5.7 and Redis 3.2.9. 

I don't have enough information to even know where to start to help you. Try to figure out why the data isn't being persisted to Redis. Walk through the application in a debugger. Is the PersonRepositoryPopulator being called?

**Comment by bermudezjuanry** [comment]
Im using java 8, spring-boot 1.5.9 and redis v=4.0.6, and the PersonRepositoryPopulator  isn't beieng calle, where must be called?

**Comment by rossr3-pivotal** [comment]
What I'm recommending is to use a debugger, set a breakpoint, and make sure that the PersonRepositoryPopulator class is being called. It is hooked into the application listener and is where the sample data gets loaded.

**Comment by bermudezjuanry** [comment]
The IDE says that PersonRepositoryPopulator is never used, that's the problem.

**Comment by rossr3-pivotal** [comment]
Just because the IDE says it is never being used, doesn't mean it really isn't being used. Dependency injection is a wonderful thing. The Spring Framework should call this at application startup. That's why I'm recommending that you use a debugger. Is it really being used? A debugger is very useful to know what is and isn't being used. IDEs can only get you so far. 

Another alternative would be to check out a tutorial I've done more recently, which is available https://github.com/rossr3-pivotal/spring-boot-workshop. It is meant to run on Pivotal Cloud Foundry, so you would need to include the RedisLocalConfig in this repo to make it run locally.

**Comment by bermudezjuanry** [comment]
Thanks for your help, was a config problem, greetings.
